/** QuicKart SCM — approved domain enums */

export type InventoryBucket =
  | 'AVAILABLE'
  | 'RESERVED'
  | 'LOCKED'
  | 'QC_HOLD'
  | 'PUTAWAY_PENDING'
  | 'DAMAGED'
  | 'EXPIRED'
  | 'IN_TRANSIT'
  | 'DISPATCH_READY'
  | 'WASTAGE'
  | 'QC_REJECTED'
  | 'RETURN_QC_HOLD'
  | 'QUARANTINE'

export type MovementType =
  | 'GRN_RECEIPT'
  | 'QC_ACCEPT'
  | 'QC_REJECT'
  | 'PUTAWAY'
  | 'RESERVATION'
  | 'RESERVATION_RELEASE'
  | 'PICK'
  | 'PICK_REVERSAL'
  | 'PACK'
  | 'DISPATCH'
  | 'TRANSFER_OUT'
  | 'TRANSFER_IN'
  | 'RETURN_RECEIPT'
  | 'RETURN_QC_ACCEPT'
  | 'RETURN_QC_REJECT'
  | 'DAMAGE'
  | 'WASTAGE'
  | 'EXPIRY'
  | 'ADJUSTMENT_IN'
  | 'ADJUSTMENT_OUT'

export type AllocationMethod = 'FIFO' | 'FEFO' | 'MANUAL'

export type PoStatus =
  | 'Draft'
  | 'Pending Approval'
  | 'Published'
  | 'Partially Received'
  | 'Received'
  | 'Closed'
  | 'Cancelled'

export type ZohoStatus = 'Not Synced' | 'Pending' | 'Synced' | 'Failed'

export type SoStatus =
  | 'Draft'
  | 'Confirmed'
  | 'Partially Reserved'
  | 'Reserved'
  | 'Picking'
  | 'Partially Picked'
  | 'Picked'
  | 'Packed'
  | 'Dispatch Ready'
  | 'Partially Dispatched'
  | 'Dispatched'
  | 'Delivered'
  | 'Cancelled'

export type ReservationStatus = 'ACTIVE' | 'PARTIALLY_CONSUMED' | 'CONSUMED' | 'RELEASED' | 'CANCELLED'
export type LockStatus = 'ACTIVE' | 'CONVERTED' | 'RELEASED' | 'EXPIRED'
export type QcResult = 'Pending' | 'Passed' | 'Failed' | 'Partial'
export type QcSourceType = 'GRN' | 'RETURN'
export type TaskStatus = 'Pending' | 'Assigned' | 'In Progress' | 'On Hold' | 'Completed' | 'Cancelled'
export type Priority = 'Low' | 'Medium' | 'High' | 'Urgent'
